# Generated by Django 4.1.5 on 2023-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_full_name_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='staff',
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='chatitg', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='chatitg', max_length=30),
        ),
    ]
