# Generated by Django 4.1.5 on 2023-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_full_name_remove_users_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(default='../static/images/Profile picture/pp.jpg', upload_to='../static/images/Profile picture/'),
        ),
    ]
