# Generated by Django 4.1.5 on 2023-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(default='/static/images/Profile picture/pp.jpg', upload_to='../static/images/Profile picture/'),
        ),
    ]
