# Generated by Django 4.1.5 on 2023-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(default='static/images/Profile_picture/pp.jpg', upload_to='static/images/Profile_picture/'),
        ),
    ]
