version: "3.9"


services:
  django:
    image: chatitg:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - pg_db
    
    links:
      - pg_db
    volumes:
      - .:/code 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - pg_db

  pg_db:
    image: postgres:15.1-alpine
    container_name: pg_db
    env_file:
      - .env


    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/



volumes:
  chatitg:
  postgres_data: